### ISSUE TITLE
下载这个音频的时候报错BV1uL411K7Bf

### ISSUE THREAD

**Issue by Bestlm** [Youguang-Zhou/bilibili-dl#1]
![image](https://user-images.githubusercontent.com/29437027/163949620-3a0bdaaf-11cc-4f78-ad5a-4add1a4af220.png)

**Comment by Bestlm** [comment]
需处理文件名转义

**Comment by Youguang-Zhou** [comment]
谢谢，已经修复了，从pip上更新一下就可以下载了：
```
pip install -U bilibili-dl
```

**Comment by Bestlm** [comment]
修改为这个，全特殊字符替换吧
out_title = re.sub('[\t\|<>\?\*\\:/\[\]]', '', out_title)

**Comment by Youguang-Zhou** [comment]
谢谢你的建议，不过这些字符并不影响本身的下载功能，所以还是暂时不改了～

**Comment by gongqiong** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Scripts\bilibili-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_dl\cli.py", line 5, in run_cli
    main(get_args())
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_dl\main.py", line 47, in main
    download(videos, is_audio_only)
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_dl\downloader.py", line 52, in download
    urllib.request.urlretrieve(download_url, raw_fname, show_progress)
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 250, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '1. What Does Schoolteachers and Sumo Wrestlers Have in Common?.raw.mp3'
