### ISSUE TITLE
invalid argument

### ISSUE THREAD

**Issue by gongqiong** [Youguang-Zhou/bilibili-dl#4]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Scripts\bilibili-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_dl\cli.py", line 5, in run_cli
    main(get_args())
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_dl\main.py", line 47, in main
    download(videos, is_audio_only)
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_dl\downloader.py", line 52, in download
    urllib.request.urlretrieve(download_url, raw_fname, show_progress)
  File "C:\Users\aboo\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 250, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '1. What Does Schoolteachers and Sumo Wrestlers Have in Common?.raw.mp3'

_Originally posted by @gongqiong in https://github.com/Youguang-Zhou/bilibili-dl/issues/1#issuecomment-2074363331_

**Comment by Youguang-Zhou** [comment]
你好，能否方便提供一下具体的BV号呢？

**Comment by gongqiong** [comment]
> argument

BV1xr421n7nX

**Comment by gongqiong** [comment]
BV1xr421n7nX

**Comment by Youguang-Zhou** [comment]
你好，可能是Windows系统对转义字符的限制不太一样，我这边没能复现出这个报错，不过我还是尝试着在新版本修复了这个问题，能麻烦您更新到最新版本后看一下还有报错吗？感谢！

```
pip install -U bilibili-dl
```

**Comment by gongqiong** [comment]
好了！
